linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/phr3nzy/duan-sssp
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocritic
        - unparam
    - path: sssp/sssp.go
      linters:
        - gocyclo  # Algorithm is inherently complex
    - path: ds/ds.go
      linters:
        - gocyclo  # Data structure operations can be complex
  exclude:
    - "SA1019.*rand.Seed"  # Allow rand.Seed for benchmark determinism
    - "commentedOutCode"  # Allow commented code for documentation

run:
  timeout: 10m
  tests: false  # Don't run tests during linting
  skip-dirs:
    - cmd/visualbench

output:
  format: colored-line-number